backend:
  name: github
media_folder: ".vuepress/public/"
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "home"
        file: "index.md"
        fields:
          - {label: Body, name: body, widget: markdown}