backend:
  name: github
  repo: p440davis/vuepress-netlify-blog
media_folder: "docs/.vuepress/public/media"
public_folder: "/media"
publish_mode: editorial_workflow
collections:
  - label: "Home"
    name: "home"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "docs/index.md"
        delete: false
        fields:
          - {label: Body, name: body, widget: markdown}
  - label: "Pages"
    name: "pages"
    folder: "docs/_pages"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Permalink", name: "permalink", widget: "hidden", default: "/:slug"}
  - label: "Posts"
    name: "posts"
    folder: "docs/_posts"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}