backend:
  name: github
  repo: p440davis/vuepress-netlify-blog
media_folder: ".vuepress/public/"
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "home"
        file: "index.md"
        fields:
          - {label: Body, name: body, widget: markdown}