backend:
  name: github
  repo: petedavisdev/petedavis.dev
media_folder: ".vuepress/public/media"
public_folder: "/media"
publish_mode: editorial_workflow
collections:
  - label: "Home"
    name: "home"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "index.md"
        delete: false
        fields:
          - label: Body
            name: body
            widget: markdown

  - label: "Page"
    name: "page"
    folder: "_pages"
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Body"
        name: "body"
        widget: "markdown"

      - label: "Permalink"
        name: "permalink"
        widget: "hidden"
        default: "/:slug"

  - label: "Post"
    name: "post"
    folder: "_posts"
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Publish Date"
        name: "date"
        widget: "date"

      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"

      - label: "Tags"
        name: "tags"
        widget: "list"
        default: ["VuePress", "Netlify CMS"]
        hint: "Comma separated list"
        required: false

      - label: "Body"
        name: "body"
        widget: "markdown"

      - label: "Permalink"
        name: "permalink"
        widget: "hidden"
        default: "/:slug"
